version: '3.4'

services:
  instaya:
    image: instaya
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
      - 3000:3000
